### ISSUE TITLE
Thumbnail icons designating quiz time are not spaced properly

### ISSUE THREAD

**Issue by hlyford11** [blakeparkinson/sports2#410]
They get cut off. Honree tried to fix but just fucked it up more.

**Comment by blakeparkinson** [comment]
@hlyford11 what are you talking about here?

**Comment by hlyford11** [comment]
See the icons on index page for the recommended quizzes; the thumbnail gets
cut off.

On Mon, Jun 8, 2015 at 11:24 PM, Blake Parkinson <notifications@github.com>
wrote:

> @hlyford11 <https://github.com/hlyford11> what are you talking about here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blakeparkinson/sports2/issues/410#issuecomment-110243194>
> .
>



-- 
*Henry Lyford*
Manager, Partnerships & Business Development
Edmodo.com/henry

**Comment by blakeparkinson** [comment]
we fixed this now
